apiVersion: apps/v1
kind: Deployment
metadata:
  name: community-insights-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: community-insights
  template:
    metadata:
      labels:
        app: community-insights
    spec:
      containers:
      - name: community-insights
        image: jackkieny/community-insights:${IMAGE_TAG}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: env-secrets
              key: SECRET_KEY
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: env-secrets
              key: MONGO_URI
        - name: MONGO_DBNAME
          valueFrom:
            secretKeyRef:
              name: env-secrets
              key: MONGO_DBNAME
        - name: MONGO_COLLECTION
          valueFrom:
            secretKeyRef:
              name: env-secrets
              key: MONGO_COLLECTION
        - name: SKOOL_LOGIN_URL
          valueFrom:
            secretKeyRef:
              name: env-secrets
              key: SKOOL_LOGIN_URL
        - name: SKOOL_COMMUNITIES_URL
          valueFrom:
            secretKeyRef:
              name: env-secrets
              key: SKOOL_COMMUNITIES_URL
        - name: SKOOL_LABELS_URL
          valueFrom:
            secretKeyRef:
              name: env-secrets
              key: SKOOL_LABELS_URL
        - name: SKOOL_POST_URL
          valueFrom:
            secretKeyRef:
              name: env-secrets
              key: SKOOL_POST_URL
      imagePullSecrets:
      - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: community-insights-loadbalancer
spec:
  selector:
    app: community-insights
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer