name: Deploy Pipeline

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up kubectl
      run: |
        curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/kubectl
    
    - name: Deploy to Kubernetes
      env:
        IMAGE_TAG: ${{ github.sha }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        MONGO_URI: ${{ secrets.MONGO_URI }}
        MONGO_DBNAME: ${{ secrets.MONGO_DBNAME }}
        MONGO_COLLECTION: ${{ secrets.MONGO_COLLECTION }}
        SKOOL_LOGIN_URL: ${{ secrets.SKOOL_LOGIN_URL }}
        SKOOL_COMMUNITIES_URL: ${{ secrets.SKOOL_COMMUNITIES_URL }}
      run: |
        echo "${{ secrets.KUBECONFIG }}" | base64 --decode > kubeconfig.yaml
        export KUBECONFIG=kubeconfig.yaml
        envsubst < deployment.yaml | kubectl apply -f -
